#Spring Boot tethys-backend configuration
spring:
  application:
    name: tethys-backend
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: morpheus
server:
  port: 80
  context-path: /
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json

