#Spring Boot tethys-backend configuration
spring:
  application:
    name: tethys-backend
server:
  port: 8000
  context-path: /
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json

# Custom properties
tethys:
  apiVersion: v1
  frontend:
    angularUrl: http://localhost:8080
    reactUrl: http://localhost:8080


# Profiles config
---
spring:
  profiles: prod
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: morpheus
---
spring:
  profiles: dev
---
spring:
  profiles:
    active: prod